// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTn2jNAfrNglefmoy29JWDWQBflEKHdlc',
    appId: '1:473568439564:web:8a72faedef987e1dcf2d29',
    messagingSenderId: '473568439564',
    projectId: 'parkito-backend-flutter',
    authDomain: 'parkito-backend-flutter.firebaseapp.com',
    storageBucket: 'parkito-backend-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3XMOLskPW29bRwWYpSYzv_z1z1yyMWDU',
    appId: '1:473568439564:android:aed9001cdb8ad93acf2d29',
    messagingSenderId: '473568439564',
    projectId: 'parkito-backend-flutter',
    storageBucket: 'parkito-backend-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUedr1t03fX4CAEZcMk86IHViEOb8aKeQ',
    appId: '1:473568439564:ios:c83b893fd3ec6f72cf2d29',
    messagingSenderId: '473568439564',
    projectId: 'parkito-backend-flutter',
    storageBucket: 'parkito-backend-flutter.appspot.com',
    iosBundleId: 'com.example.parkitoBackendFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUedr1t03fX4CAEZcMk86IHViEOb8aKeQ',
    appId: '1:473568439564:ios:25d64e516f4825b9cf2d29',
    messagingSenderId: '473568439564',
    projectId: 'parkito-backend-flutter',
    storageBucket: 'parkito-backend-flutter.appspot.com',
    iosBundleId: 'com.example.parkitoBackendFlutter.RunnerTests',
  );
}
